// Russian confectionery lexicon: maps the words the pastry chefs actually wrote in the
// tortufa.ru product descriptions onto a renderable layer (kind, colour, texture).
// Order matters — the most specific phrase has to win, so this list is scanned top-down.

export const LEX = [
  // ---------- SPONGES / BASES ----------
  { re: /красн\w+ бархат|бархат/i, kind: 'sponge', label: 'Бисквит «Красный бархат»', color: '#A62A2E', tex: 'velvet' },
  { re: /бисквит\w*\s*(?:с\s*)?фисташк|фисташков\w+ бисквит/i, kind: 'sponge', label: 'Фисташковый бисквит', color: '#A8BE6C', tex: 'sponge' },
  { re: /бисквит\w*\s*с\s*маком|с\s*маком/i, kind: 'sponge', label: 'Бисквит с маком', color: '#E2D0AB', tex: 'poppy' },
  { re: /с\s*кураг/i, kind: 'sponge', label: 'Бисквит с курагой', color: '#EBC486', tex: 'apricot-bits' },
  { re: /с\s*изюм/i, kind: 'sponge', label: 'Бисквит с изюмом', color: '#E6CFA6', tex: 'raisin' },
  { re: /бисквит\w*\s*с\s*грецк\w+ орех|бисквит\w*\s*(?:с\s*)?орех/i, kind: 'sponge', label: 'Бисквит с грецким орехом', color: '#DFC596', tex: 'walnut' },
  { re: /постн\w+ (?:шоколадн\w+ )?бисквит|бисквит\w*\s*постн/i, kind: 'sponge', label: 'Постный бисквит', color: '#E7D2A6', tex: 'sponge', lenten: true },
  { re: /шоколадн\w+ бисквит|бисквит\w*\s*шоколадн|бисквит\w*\s*(?:с\s*)?какао/i, kind: 'sponge', label: 'Шоколадный бисквит', color: '#57351F', tex: 'cocoa' },
  { re: /сметанн\w+ бисквит|бисквит\w*\s*сметанн/i, kind: 'sponge', label: 'Сметанный бисквит', color: '#F0DEBE', tex: 'sponge' },
  { re: /бисквит\w*\s*на\s*кефире/i, kind: 'sponge', label: 'Бисквит на кефире', color: '#EFDDB8', tex: 'sponge' },
  { re: /молочн\w+ бисквит|бисквит\w*\s*молочн/i, kind: 'sponge', label: 'Воздушный молочный бисквит', color: '#F5E4C3', tex: 'airy' },
  { re: /бел\w+ заварн\w+ бисквит|бисквит\w*\s*бел\w+ заварн/i, kind: 'sponge', label: 'Белый заварной бисквит', color: '#F3E0B6', tex: 'sponge' },
  { re: /заварн\w+ бисквит/i, kind: 'sponge', label: 'Заварной бисквит', color: '#F1DDB0', tex: 'sponge' },
  { re: /ванильн\w+ бисквит|бисквит\w*\s*ванильн/i, kind: 'sponge', label: 'Ванильный бисквит', color: '#EFD59C', tex: 'sponge' },
  { re: /медов\w+/i, kind: 'sponge', label: 'Медовые коржи', color: '#D79A4C', tex: 'honey' },
  { re: /песочн\w+/i, kind: 'sponge', label: 'Песочный корж', color: '#DEAD6A', tex: 'shortcrust' },
  { re: /слоен\w+ п\/ф|слоён\w+ п\/ф|слоен\w+ полуфабрикат/i, kind: 'sponge', label: 'Слоёный полуфабрикат', color: '#E9CB97', tex: 'puff' },
  { re: /мука в\/с|песочн\w+ крошк/i, kind: 'sponge', label: 'Песочная крошка', color: '#DEAD6A', tex: 'shortcrust' },
  { re: /бисквит/i, kind: 'sponge', label: 'Бисквит', color: '#EFD59C', tex: 'sponge' },

  // ---------- CREAMS ----------
  { re: /крем\s*цюрих|цюрих/i, kind: 'cream', label: 'Крем «Цюрих»', color: '#7B4E31', tex: 'cream' },
  { re: /крем[\s-]*чиз|сырн\w+ крем|крем\w*\s*«?чиз/i, kind: 'cream', label: 'Крем-чиз', color: '#FFF8EC', tex: 'cheese' },
  { re: /мусс\w*\s*йогуртов\w*[-\s]*клубничн|йогуртов\w*[-\s]*клубничн\w+ мусс/i, kind: 'cream', label: 'Йогуртово-клубничный мусс', color: '#F6C2C8', tex: 'mousse' },
  { re: /\bмусс\w*/i, kind: 'cream', label: 'Мусс', color: '#FBE3DC', tex: 'mousse' },
  { re: /суфле/i, kind: 'cream', label: 'Суфле', color: '#FFFAF0', tex: 'souffle' },
  { re: /сливочно[-\s]*шоколадн\w+ крем|крем\w*\s*сливочно[-\s]*шоколадн/i, kind: 'cream', label: 'Сливочно-шоколадный крем', color: '#7C4F32', tex: 'cream' },
  { re: /крем\w*\s*из\s*сливок\s*шоколадн|шоколадн\w+ крем\w*\s*из\s*сливок/i, kind: 'cream', label: 'Шоколадный крем из сливок', color: '#7C4F32', tex: 'cream' },
  { re: /крем\w*\s*из\s*творога|творожн\w+ крем/i, kind: 'cream', label: 'Творожный крем со сливками', color: '#FDF7EA', tex: 'curd' },
  { re: /сливк\w*\s*с\s*варен\w+ сгущ|крем\w*\s*из\s*сливок\s*с\s*варен\w+ сгущ|прослойка\w*\s*из\s*вар\w+ сгущ|сливочн\w+ крем\w*\s*со?\s*сгущ|молоко сгущеное варен/i, kind: 'cream', label: 'Сливки с варёной сгущёнкой', color: '#C98A45', tex: 'caramel-cream' },
  { re: /заварн\w+ крем\w*\s*со\s*сметан|крем\w*\s*заварн\w+ со\s*сметан/i, kind: 'cream', label: 'Заварной крем со сметаной', color: '#FAEDCE', tex: 'custard' },
  { re: /сливочно[-\s]*заварн\w+ крем/i, kind: 'cream', label: 'Сливочно-заварной крем', color: '#FBEBC6', tex: 'custard' },
  { re: /заварн\w+ крем|крем\w*\s*заварн/i, kind: 'cream', label: 'Заварной крем', color: '#FBE9C0', tex: 'custard' },
  { re: /сливочн\w+ крем\w*\s*со?\s*сметан|крем\w*\s*сливочн\w+ со\s*сметан/i, kind: 'cream', label: 'Сливочный крем со сметаной', color: '#FBF2DF', tex: 'cream' },
  { re: /сметанн\w+ крем|крем\w*\s*сметанн/i, kind: 'cream', label: 'Сметанный крем', color: '#FCF4E2', tex: 'cream' },
  { re: /постн\w+ крем|крем\w*\s*постн/i, kind: 'cream', label: 'Постный крем из сливок', color: '#FFFBF2', tex: 'cream', lenten: true },
  { re: /сливки\s*растительн|растительн\w+ сливк/i, kind: 'cream', label: 'Растительные сливки', color: '#FFFCF5', tex: 'cream', lenten: true },
  { re: /взбит\w+ сливк/i, kind: 'cream', label: 'Взбитые сливки', color: '#FFFDF8', tex: 'whipped' },
  { re: /крем\w*\s*из\s*сливок|сливочн\w+ крем|крем\w*\s*сливочн/i, kind: 'cream', label: 'Крем из сливок', color: '#FFFDF6', tex: 'cream' },
  { re: /\bкрем\b/i, kind: 'cream', label: 'Нежный крем', color: '#FFFCF2', tex: 'cream' },

  // ---------- FILLINGS ----------
  { re: /лимонн\w+ конфитюр|конфитюр\w*\s*лимонн/i, kind: 'fill', label: 'Лимонный конфитюр', color: '#F3C138', tex: 'jam' },
  { re: /жел\w+ из малин|малинов\w+ жел/i, kind: 'fill', label: 'Малиновое желе', color: '#C21E45', tex: 'jelly' },
  { re: /конфитюр\w*\s*«?малин|малинов\w+ конфитюр/i, kind: 'fill', label: 'Малиновый конфитюр', color: '#C21E45', tex: 'jam' },
  { re: /конфитюр\w*\s*«?(?:чёрн|черн)\w+ смородин|конфитюр\w*\s*«?смородин/i, kind: 'fill', label: 'Конфитюр «Чёрная смородина»', color: '#4A1E3D', tex: 'jam' },
  { re: /персиков\w+ конфитюр|конфитюр\w*\s*персик/i, kind: 'fill', label: 'Персиковый конфитюр', color: '#F2A65A', tex: 'jam' },
  { re: /клубничн\w+ гель|гель\w*\s*клубничн/i, kind: 'fill', label: 'Клубничный гель', color: '#D9304A', tex: 'gel' },
  { re: /карамельн\w+ гель|гель\w*\s*«?карамельн/i, kind: 'fill', label: 'Карамельный гель', color: '#C9862F', tex: 'gel' },
  { re: /карамель\w*\s*сол[её]н|сол[её]н\w+ карамель/i, kind: 'fill', label: 'Солёная карамель', color: '#C07A2E', tex: 'gel' },
  { re: /яблочн\w+ повидло|повидло/i, kind: 'fill', label: 'Яблочное повидло', color: '#C98A3E', tex: 'jam' },
  { re: /фруктов\w+ жел|жел\w+ фруктов/i, kind: 'fill', label: 'Фруктовое желе', color: '#E4544F', tex: 'jelly' },
  { re: /фруктово[-\s]*ягодн\w+ наполнител/i, kind: 'fill', label: 'Фруктово-ягодный наполнитель', color: '#DC5B3C', tex: 'jam' },
  { re: /5 видов конфитюра|конфитюр\w*\s*с\s*кусочками/i, kind: 'fill', label: 'Пять конфитюров с кусочками', color: '#DE6A34', tex: 'jam' },
  { re: /шокодел/i, kind: 'fill', label: 'Шокодель', color: '#43281A', tex: 'choco' },
  { re: /конфитюр/i, kind: 'fill', label: 'Конфитюр', color: '#CE4436', tex: 'jam' },
  { re: /\bгель\b/i, kind: 'fill', label: 'Ягодный гель', color: '#CE4436', tex: 'gel' },
  { re: /смородин/i, kind: 'fill', label: 'Смородина', color: '#4A1E3D', tex: 'jam' },

  // ---------- GLAZES / TOPS ----------
  { re: /ганаш\w*\s*с\s*бел\w+ шоколад|бел\w+ ганаш/i, kind: 'top', label: 'Ганаш из белого шоколада', color: '#F1E0BE', tex: 'ganache' },
  { re: /шоколадн\w+ ганаш|ганаш/i, kind: 'top', label: 'Шоколадный ганаш', color: '#3C2216', tex: 'ganache' },
  { re: /бел\w+ шоколадн\w+ глазур|бел\w+ глазур/i, kind: 'top', label: 'Белая глазурь', color: '#FBF3E4', tex: 'glaze' },
  { re: /шоколадн\w+ глазур|глазур\w*\s*шоколадн/i, kind: 'top', label: 'Шоколадная глазурь', color: '#3F2317', tex: 'glaze' },
  { re: /шоколадн\w+ помадк/i, kind: 'top', label: 'Шоколадная помадка', color: '#4E2E1E', tex: 'fondant' },
  { re: /сахарн\w+ помадк|помадк/i, kind: 'top', label: 'Сахарная помадка', color: '#FCF6EA', tex: 'fondant' },
  { re: /глазур/i, kind: 'top', label: 'Глазурь', color: '#F7EEDC', tex: 'glaze' },

  // ---------- CRUNCH / DECOR ----------
  { re: /меренг/i, kind: 'crunch', label: 'Хрустящая меренга', color: '#FFF6E3', tex: 'meringue' },
  { re: /ореховое пралине|пралине/i, kind: 'crunch', label: 'Ореховое пралине', color: '#B8814A', tex: 'nuts' },
  { re: /грецк\w+ орех/i, kind: 'crunch', label: 'Грецкий орех', color: '#C08A52', tex: 'nuts' },
  { re: /арахис/i, kind: 'crunch', label: 'Арахис', color: '#C79157', tex: 'nuts' },
  { re: /трюфельн\w+ крошк/i, kind: 'crunch', label: 'Трюфельная крошка', color: '#4A2C1C', tex: 'crumb' },
  { re: /шоколадн\w+ крошк/i, kind: 'crunch', label: 'Шоколадная крошка', color: '#4A2C1C', tex: 'crumb' },
  { re: /бисквитн\w+ крошк/i, kind: 'crunch', label: 'Бисквитная крошка', color: '#D8B583', tex: 'crumb' },
  { re: /сло[её]н\w+ крошк/i, kind: 'crunch', label: 'Слоёная крошка', color: '#E0C08A', tex: 'crumb' },
  { re: /шоколадн\w+ посыпк/i, kind: 'crunch', label: 'Шоколадная посыпка', color: '#3F2317', tex: 'sprinkle' },
  { re: /макарун|макарон/i, kind: 'crunch', label: 'Пирожные макарун', color: '#F3B7C4', tex: 'macaron' },
  { re: /мармелад/i, kind: 'crunch', label: 'Мармелад', color: '#E0453F', tex: 'marmalade' },
  { re: /полуфабрикатs*«?картошка|пирожнw*s*«?картошка/i, kind: 'crunch', label: 'Полуфабрикат «Картошка»', color: '#5A3A24', tex: 'crumb' },
  { re: /посыпк\w*\s*сердечк/i, kind: 'crunch', label: 'Посыпка «Сердечки»', color: '#E8607A', tex: 'sprinkle' },
  { re: /крошк/i, kind: 'crunch', label: 'Крошка', color: '#D8B583', tex: 'crumb' },
  { re: /шоколад(?!н)/i, kind: 'crunch', label: 'Шоколад', color: '#43281A', tex: 'choco' },
]

// Fruit pieces named inside a filling — rendered as inclusions in the jam band.
export const FRUITS = [
  { re: /абрикос/i, label: 'абрикос', color: '#E89B3C' },
  { re: /груш/i, label: 'груша', color: '#DCCB7A' },
  { re: /клубник/i, label: 'клубника', color: '#D9304A' },
  { re: /вишн/i, label: 'вишня', color: '#8E1B2C' },
  { re: /киви/i, label: 'киви', color: '#8DB33F' },
  { re: /малин/i, label: 'малина', color: '#C21E45' },
  { re: /смородин/i, label: 'смородина', color: '#4A1E3D' },
  { re: /апельсин/i, label: 'апельсин', color: '#EE8B2B' },
  { re: /персик/i, label: 'персик', color: '#F2A65A' },
  { re: /лимон/i, label: 'лимон', color: '#F3C138' },
  { re: /яблок|яблочн/i, label: 'яблоко', color: '#C4D24B' },
  { re: /фисташк/i, label: 'фисташка', color: '#A8BE6C' },
  { re: /кураг/i, label: 'курага', color: '#E0902F' },
  { re: /изюм/i, label: 'изюм', color: '#5C3B2E' },
  { re: /\bмак\b|маком/i, label: 'мак', color: '#3A3340' },
]
